# Generated by Django 3.0.8 on 2020-07-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255, verbose_name='Name of Item')),
                ('itemDescription', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description of Item')),
                ('itemPrice', models.BigIntegerField(max_length=16, verbose_name='Price of Item')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
            ],
        ),
    ]
