# Generated by Django 3.0.8 on 2020-07-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoCrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='itemPrice',
            field=models.BigIntegerField(verbose_name='Price of Item'),
        ),
    ]
